# Generated by Django 4.2.2 on 2023-06-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=15, unique=True)),
                ('pnombre', models.CharField(max_length=15)),
                ('snombre', models.CharField(max_length=15)),
                ('appaterno', models.CharField(max_length=15)),
                ('apmaterno', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=30)),
                ('contrasena', models.CharField(max_length=15)),
                ('telefono', models.IntegerField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
