# Generated by Django 4.2.2 on 2023-07-11 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carta', models.CharField(max_length=70)),
                ('imagen', models.ImageField(upload_to='foto_carta/')),
                ('carta_reeditada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mazo', models.CharField(max_length=10)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apmaterno', models.CharField(max_length=15)),
                ('telefono', models.PositiveSmallIntegerField()),
                ('foto_usuario', models.ImageField(upload_to='foto_usuario/')),
                ('fk_id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcturian_app.region')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcturian_app.carta')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcturian_app.mazo')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(max_length=50)),
                ('fk_id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcturian_app.region')),
            ],
        ),
    ]
